### ISSUE TITLE
ubuntu 16+pyhton3.5环境下运行失败

### ISSUE THREAD

**Issue by d100972** [huanglizhuo/TWchat#1]
Traceback (most recent call last):
  File "/usr/local/bin/twchat", line 7, in <module>
    from TWchat import start
  File "/usr/local/lib/python3.5/dist-packages/TWchat/__init__.py", line 3, in <module>
    import gui as wegui
ImportError: No module named 'gui'

tkinter已经安装。

**Comment by huanglizhuo** [comment]
目前只支持py2 
py3 兼容版本还在开发中
